# Generated by Django 3.2.14 on 2022-07-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('email', models.CharField(db_column='Email', max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(db_column='Password', max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
